name: Generate Datas

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

permissions:          # <-- AQUI
  contents: write
  pages: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: deividjmoura
          svg_out_path: dist/github-contribution-grid-snake.svg

            # Snake viva (fork mantido)
      - uses: Ashutosh00710/snake@master
        id: snake-gif
        with:
          github_user_name: deividjmoura
          gif_out_path: dist/snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
